version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db  # ensures DB starts before pgAdmin
    restart: always

  pipeline:
    build: ./pipeline   # path to your Python Dockerfile
    container_name: pipeline
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/ny_taxi
    restart: "no"  # run once, then exit

